try-catch-finally处理机制示意图
try{
    代码/可能有异常
}catch(Exception e){
    捕获到异常
    1、当异常发生时
    2、系统将异常封装成Exception 对象 赋值给 对象名 e，传递给catch
    3、得到异常对象后，程序员，自己处理
    4、注意如果没有发生异常
    catch块不执行
}finally{
    1、不管try块是否有异常发生，始终哟啊执行finally
    2、所以通常将释放资源的代码，放在finally（什么是释放资源的代码）
    3、finally块可有可无
}


如果没有catch语句代码 try语句中的代码发生异常,则直接结束程序.